---
- name: Collecting facts
  hosts: all
  gather_facts: yes

- hosts: ceph_osd
  name: get facts
  tasks:
    - action: get_partitions.py

- hosts: ceph_mon
  tasks:
    - include: ceph/tasks/mon_0.yml
      when: inventory_hostname == groups.ceph_mon[0]

- hosts: ceph_mon
  tasks:
    - include: ceph/tasks/mon.yml
      when: inventory_hostname != groups.ceph_mon[0]

- hosts: ceph_osd
  tasks:
    - include: ceph/tasks/osd.yml