---
- name: Copying keyring from mon.0
  copy: src=/tmp/fetched.ceph.keyring dest=/etc/ceph/ceph.keyring owner=root group=root mode=644 backup=yes

- name: Copying monmap from mon.0
  copy: src=/tmp/fetched.monmap dest=/etc/ceph/monmap owner=root group=root mode=644 backup=yes

- name: configure ceph with fsid from monmap
  template: src=ceph/templates/etc/ceph/ceph.conf.j2 dest=/etc/ceph/ceph.conf owner=root group=root mode=0644
  when: monmap1.changed

- name: Create ceph working directory
  file: path=/var/lib/ceph/mon/ceph-{{ inventory_hostname_short }} state=directory

- name: copy keyring in /var/lib/ceph/mon/ceph-{{ inventory_hostname_short }}
  shell: creates=/var/lib/ceph/mon/ceph-{{ inventory_hostname_short }}/keyring cp -a /etc/ceph/ceph.keyring /var/lib/ceph/mon/ceph-{{ inventory_hostname_short }}/keyring 

- name: Create mon fs
  shell: creates=/var/run/ceph/mon.{{ inventory_hostname_short }}.pid ceph-mon --keyring /etc/ceph/ceph.keyring -i {{ inventory_hostname_short }} --mkfs --monmap /etc/ceph/monmap

- name: Touch something for the sake of touching it mwahaha
  shell: creates=/var/lib/ceph/mon/ceph-{{ inventory_hostname_short }}/sysvinit touch /var/lib/ceph/mon/ceph-{{ inventory_hostname_short }}/sysvinit

- name: Ensure ceph-mon is running
  service: name=ceph state=started pattern=ceph-mon enabled=yes