---
# To do only on the *first* mon client
- name: Create key for client.admin and mon. on the first mon node
  shell: creates=/etc/ceph/ceph.keyring ceph-authtool --create-keyring --gen-key -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' /etc/ceph/ceph.keyring; ceph-authtool --gen-key -n mon. /etc/ceph/ceph.keyring --cap mon 'allow *'
  register: client_admin_key

- name: Create monmap on the first mon node and store fsid in a dedicated file
  shell: creates=/etc/ceph/monmap monmaptool --create --add {{ inventory_hostname_short }} {{ hostvars[inventory_hostname_short]['ansible_eth2']['ipv4']['address'] }}:6789 /etc/ceph/monmap | grep fsid | awk {'print $4'} >> /etc/ceph/fsid
  register: monmap1

- name: Create ceph working directory
  file: path=/var/lib/ceph/mon/ceph-{{ inventory_hostname_short }} state=directory

- name: Create local Ceph FileSystem
  command: ceph-mon --keyring /etc/ceph/ceph.keyring -i {{ inventory_hostname_short }} --mkfs --monmap /etc/ceph/monmap 
      creates=/var/lib/ceph/mon/ceph-{{ inventory_hostname_short }}/store.db/LOCK

# Not using file here because it will always touch, my version will only touch when file not there
- name: Touch something for the sake of touching it mwahaha
  shell: creates=/var/lib/ceph/mon/ceph-{{ inventory_hostname_short }}/sysvinit touch /var/lib/ceph/mon/ceph-{{ inventory_hostname_short }}/sysvinit

# Screw this and put it directly to the generation task - maybe?
- name: read fsid from file into global ansible var
  local_command: cat /etc/ceph/fsid
  register: monmap

- name: configure ceph with fsid from monmap
  template: src=ceph/templates/etc/ceph/ceph.conf.j2 dest=/etc/ceph/ceph.conf owner=root group=root mode=0644
  when: monmap1.changed

- name: Create key for OSD bootstrap
  shell: ceph-authtool --create-keyring --gen-key -n client.bootstrap-osd --cap mon 'allow profile bootstrap-osd' /etc/ceph/ceph.keyring.bootstrap-osd creates="/etc/ceph/ceph.keyring.bootstrap-osd"
  register: bootstrap

#Cleanup local hdd (admin ws)
- name: Download the key from mon_0
  fetch: src=/etc/ceph/ceph.keyring dest=/tmp/fetched.ceph.keyring flat=yes fail_on_missing=yes

#Cleanup local hdd (admin ws)
- name: Download the OSD Bootstrap key from mon_0
  fetch: src=/etc/ceph/ceph.keyring.bootstrap-osd dest=/tmp/fetched.ceph.keyring.bootstrap-osd flat=yes fail_on_missing=yes

#Cleanup local hdd (admin ws)
- name: Download the monmap from mon_0
  fetch: src=/etc/ceph/monmap dest=/tmp/fetched.monmap flat=yes fail_on_missing=yes

- name: Ensure ceph-mon is running
  service: name=ceph state=started pattern=/usr/bin/ceph-mon enabled=yes

- name: feed our OSD bootstrap key to the cluster
  shell: ceph auth add client.bootstrap-osd -i /etc/ceph/ceph.keyring.bootstrap-osd
  when: bootstrap.changed