---
- name: configure ceph with fsid from monmap
  template: src=ceph/templates/etc/ceph/ceph.conf.j2 dest=/etc/ceph/ceph.conf owner=root group=root mode=644 backup=yes

- name: Upload the OSD Bootstrap key from mon_0
  copy: content=/tmp/fetched.ceph.keyring.bootstrap-osd dest=/var/lib/ceph/bootstrap-osd/ceph.keyring owner=root group=root mode=644 

- name: Prepare Disks that are not active
  command: ceph-disk prepare --zap-disk /dev/{{ item }}
  when_set: item
  with_items: ceph_devs

# TODO: get facts about already prepped but not activated disks aswell
- name: Mark prepared disk as active
  shell: ceph-disk activate /dev/{{ item }}
  when_set: item
  with_items: ceph_devs

- name: Ensure ceph-osd is running
  action: service name=ceph state=started